"""
eda_service.py

Service module for loading and serving pre-computed EDA cache.
The cache is generated by compute_eda_cache.py and loaded once at Flask startup.

Usage:
    from app.services.eda_service import load_eda_cache, get_eda_data
    load_eda_cache("path/to/eda_cache.json")
    data = get_eda_data()
"""

import json
import logging
from pathlib import Path
from typing import Optional, Dict, Any

logger = logging.getLogger(__name__)

_EDA_CACHE: Optional[Dict[str, Any]] = None


def load_eda_cache(cache_path: str) -> Dict[str, Any]:
    """
    Load EDA cache from JSON file into memory.

    Args:
        cache_path: Path to eda_cache.json

    Returns:
        Loaded EDA data dict

    Raises:
        FileNotFoundError: If cache file doesn't exist
        json.JSONDecodeError: If cache is invalid JSON
        ValueError: If cache structure is invalid
    """
    global _EDA_CACHE

    cache_path = Path(cache_path)
    print(f"Loading EDA cache from {cache_path}")

    if not cache_path.exists():
        raise FileNotFoundError(f"EDA cache not found at {cache_path}")

    try:
        with open(cache_path, 'r', encoding='utf-8') as f:
            _EDA_CACHE = json.load(f)

        _validate_cache_structure(_EDA_CACHE)

        logger.info(f"Loaded EDA cache from {cache_path}")
        logger.info(
            f"Cache computed at: {_EDA_CACHE.get('metadata', {}).get('computed_at')}"
        )

        return _EDA_CACHE

    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in EDA cache: {e}")
        raise
    except ValueError as e:
        logger.error(f"Invalid EDA cache structure: {e}")
        raise


def _validate_cache_structure(cache: Dict[str, Any]) -> None:
    """Validate that cache has required sections."""
    required_keys = {
        'metadata',
        'overview',
        'top_features',
        'feature_distributions',
    }

    missing = required_keys - set(cache.keys())
    if missing:
        raise ValueError(f"EDA cache missing required keys: {missing}")

    if not isinstance(cache['metadata'], dict):
        raise ValueError("metadata must be a dict")
    if not isinstance(cache['overview'], dict):
        raise ValueError("overview must be a dict")
    if not isinstance(cache['top_features'], list):
        raise ValueError("top_features must be a list")
    if not isinstance(cache['feature_distributions'], dict):
        raise ValueError("feature_distributions must be a dict")


def get_eda_data() -> Dict[str, Any]:
    """
    Retrieve the cached EDA data.

    Returns:
        Full cache dict with all computed statistics

    Raises:
        RuntimeError: If cache hasn't been loaded yet
    """
    if _EDA_CACHE is None:
        raise RuntimeError('EDA cache not loaded. Call load_eda_cache() first.')

    return _EDA_CACHE


def get_eda_section(section_name: str) -> Any:
    """
    Retrieve a specific section of EDA data.

    Available sections:
        - metadata: Computation metadata (timestamp, data path, etc.)
        - overview: Dataset statistics (size, class distribution, imbalance)
        - top_features: Top predictive features ranked by effect size
        - feature_categories: Summary stats for feature categories
        - feature_distributions: Histograms for all numeric features
        - profanity_slang: Profanity and slang analysis
        - identity_analysis: Identity mention risk analysis
        - text_shape: Text structure pattern analysis
        - correlations: Feature correlation matrix

    Args:
        section_name: Name of the EDA section

    Returns:
        Data for that section, or None if not found

    Raises:
        RuntimeError: If cache hasn't been loaded yet
    """
    if _EDA_CACHE is None:
        raise RuntimeError('EDA cache not loaded. Call load_eda_cache() first.')

    return _EDA_CACHE.get(section_name)


def is_eda_cache_loaded() -> bool:
    """Check if EDA cache is currently loaded."""
    return _EDA_CACHE is not None


def clear_eda_cache() -> None:
    """Clear cached EDA data (useful for testing)."""
    global _EDA_CACHE
    _EDA_CACHE = None
