# -*- coding: utf-8 -*-
"""eda_v1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfwT5TSDLl-ly3zZR1Bm8rlrTMKVMKNX

# Reproducible EDA Notebook (EDA-1 to EDA-5)

This notebook runs exploratory data analysis using the already prepared processed files.

- `TRAIN_DATA_PATH` points to the train split with engineered features.
- `TEST_DATA_PATH` points to the raw test split (no engineered features).
- Paths are relative to the repository root.
- The train/test split is already done and is **not** recreated here.
- `TARGET_COLUMN` is set explicitly in the config cell.
"""

# Core imports
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Display settings
pd.set_option("display.max_columns", 200)
sns.set_theme(style="whitegrid", context="notebook")

# -------------------------
# User-configurable settings
# -------------------------
# Paths are relative to this notebook directory: 00_analysis/05_EDA/
TRAIN_DATA_PATH = "../../01_data/01_processed/train_set_with_features.csv"
TEST_DATA_PATH = "../../01_data/01_processed/test_raw.csv"
TARGET_COLUMN = "toxic"
PROBLEM_TYPE = "classification"

# Load processed train split with engineered features
# and raw test split for representativeness checks.
df = pd.read_csv(TRAIN_DATA_PATH)
df_test = pd.read_csv(TEST_DATA_PATH)

print(f"Loaded train file: {TRAIN_DATA_PATH}")
print(f"Train shape: {df.shape}")
print(f"Loaded test file:  {TEST_DATA_PATH}")
print(f"Test shape:  {df_test.shape}")
display(df.head())

"""## EDA-1: Initial Report

This section covers the dataset overview, missing values, duplicates, and data-type composition.
"""

# Basic structure and summary stats
display(df.info())
display(df.describe(include="all").T)

# Missing values report
missing_counts = df.isna().sum().sort_values(ascending=False)
missing_pct = (df.isna().mean() * 100).sort_values(ascending=False)
missing_report = pd.DataFrame({"missing_count": missing_counts, "missing_pct": missing_pct})
display(missing_report[missing_report["missing_count"] > 0])

# Duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Duplicate rows: {duplicate_count}")

# Data types visualization
dtype_counts = df.dtypes.astype(str).value_counts()
plt.figure(figsize=(8, 4))
sns.barplot(x=dtype_counts.index, y=dtype_counts.values, palette="viridis")
plt.title("Feature Count by Data Type")
plt.xlabel("Data Type")
plt.ylabel("Number of Columns")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

"""### Key Observations (EDA-1)
- No missing Values
- No duplicate rows

## EDA-2: Outcome Variable Deep Dive

This section analyzes only the outcome variable for class distribution and imbalance.
"""

if TARGET_COLUMN not in df.columns:
    raise ValueError(
        f"TARGET_COLUMN='{TARGET_COLUMN}' not found. Update TARGET_COLUMN at top."
    )

plt.figure(figsize=(8, 4))
ax = sns.countplot(data=df, x=TARGET_COLUMN, order=df[TARGET_COLUMN].value_counts().index)
plt.title(f"Target Class Distribution: {TARGET_COLUMN}")
plt.xlabel(TARGET_COLUMN)
plt.ylabel("Count")
for p in ax.patches:
    h = p.get_height()
    ax.annotate(f"{int(h)}", (p.get_x() + p.get_width() / 2, h), ha="center", va="bottom")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

target_counts = df[TARGET_COLUMN].value_counts(dropna=False)
target_pct = df[TARGET_COLUMN].value_counts(normalize=True, dropna=False) * 100
display(pd.DataFrame({"count": target_counts, "pct": target_pct.round(2)}))

# Imbalance ratio (majority/minority) for classification
if len(target_counts) > 1:
    imbalance_ratio = target_counts.max() / target_counts.min()
    print(f"Imbalance ratio (majority/minority): {imbalance_ratio:.2f}")
else:
    print("Only one class detected in target.")

"""### Key Observations (EDA-2)

- Huge class imbalance toxic (1/0)
-stratification and/or class weighting  be needed later

## EDA-3: Train-Test Split Check (Leakage-Safe)

The split is already done. This section verifies representativeness and confirms leakage-safe setup before feature-level EDA on train only.
"""

# Split representativeness checks (split already created upstream)
print(f"Train shape: {df.shape}")
print(f"Test shape:  {df_test.shape}")

if TARGET_COLUMN in df.columns and TARGET_COLUMN in df_test.columns:
    train_target_rate = df[TARGET_COLUMN].mean()
    test_target_rate = df_test[TARGET_COLUMN].mean()
    abs_gap = abs(train_target_rate - test_target_rate)

    print(f"Train {TARGET_COLUMN} rate: {train_target_rate:.4f}")
    print(f"Test  {TARGET_COLUMN} rate: {test_target_rate:.4f}")
    print(f"Absolute rate gap: {abs_gap:.4f}")

    split_report = pd.DataFrame(
        {
            "split": ["train", "test"],
            "rows": [len(df), len(df_test)],
            f"{TARGET_COLUMN}_rate": [train_target_rate, test_target_rate],
        }
    )
    display(split_report)
else:
    print(f"Target column '{TARGET_COLUMN}' missing in one of the splits.")

"""### Key Observations (EDA-3)

- Split is already provided and treated as fixed input.
- Train/test row counts are validated in the check cell.
- Target-rate gap between train and test is reported directly.
- Feature-level EDA remains train-only to stay leakage-safe.

## EDA-4: Feature-Level Deep Dive (Train Set Only)

This section analyzes engineered numeric features from `train_set_with_features.csv` and their relationship with the target.
"""

# Numeric-feature analysis on train split only
exclude_cols = {
    "id",
    "comment_text",
    TARGET_COLUMN,
    "severe_toxic",
    "obscene",
    "threat",
    "insult",
    "identity_hate",
}

numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in exclude_cols
]

print(f"Numeric feature columns analyzed: {len(numeric_cols)}")

# Occurrence table: how often each feature is non-zero
occurrence_df = pd.DataFrame(index=numeric_cols)
occurrence_df["non_zero_count"] = (df[numeric_cols] != 0).sum(axis=0)
occurrence_df["non_zero_pct"] = (occurrence_df["non_zero_count"] / len(df) * 100).round(2)

if TARGET_COLUMN in df.columns:
    non_toxic_mask = df[TARGET_COLUMN] == 0
    toxic_mask = df[TARGET_COLUMN] == 1

    occurrence_df["non_zero_count_non_toxic"] = (df.loc[non_toxic_mask, numeric_cols] != 0).sum(axis=0)
    occurrence_df["non_zero_count_toxic"] = (df.loc[toxic_mask, numeric_cols] != 0).sum(axis=0)
    occurrence_df["non_zero_pct_non_toxic"] = (
        occurrence_df["non_zero_count_non_toxic"] / max(non_toxic_mask.sum(), 1) * 100
    ).round(2)
    occurrence_df["non_zero_pct_toxic"] = (
        occurrence_df["non_zero_count_toxic"] / max(toxic_mask.sum(), 1) * 100
    ).round(2)

occurrence_df = occurrence_df.sort_values("non_zero_count", ascending=False)
print("Feature occurrence (non-zero) in training data:")
display(occurrence_df)

# Correlation with target (absolute, strongest first)
feature_target_corr = (
    df[numeric_cols + [TARGET_COLUMN]]
    .corr(numeric_only=True)[TARGET_COLUMN]
    .drop(TARGET_COLUMN)
    .sort_values(key=lambda s: s.abs(), ascending=False)
)
display(feature_target_corr.to_frame(name=f"corr_with_{TARGET_COLUMN}").head(15))

# Compare feature means by target class
feature_means = (
    df.groupby(TARGET_COLUMN)[numeric_cols]
    .mean()
    .T
    .rename(columns={0: "non_toxic", 1: "toxic"})
)
feature_means["toxic_minus_non_toxic"] = feature_means["toxic"] - feature_means["non_toxic"]
feature_means = feature_means.sort_values(
    "toxic_minus_non_toxic", key=lambda s: s.abs(), ascending=False
)
display(feature_means.head(15))

# Correlation heatmap for top correlated features
top_corr_features = feature_target_corr.head(12).index.tolist()
if top_corr_features:
    plt.figure(figsize=(10, 8))
    sns.heatmap(
        df[top_corr_features + [TARGET_COLUMN]].corr(numeric_only=True),
        cmap="coolwarm",
        center=0,
        annot=False,
    )
    plt.title("Correlation Heatmap (Top Features + Target)")
    plt.tight_layout()
    plt.show()

# Distribution plots for top 6 features
for col in top_corr_features[:6]:
    plt.figure(figsize=(8, 4))
    sns.histplot(data=df, x=col, hue=TARGET_COLUMN, bins=40, stat="density", common_norm=False)
    plt.title(f"Distribution by {TARGET_COLUMN}: {col}")
    plt.tight_layout()
    plt.show()

"""### Key Observations (EDA-4)

- The strongest signal comes from sentiment negativity (`vader_neg`), while `vader_compound` and `vader_pos_minus_neg` decrease as toxicity increases.
- Direct-address features (`second_person_density`, `has_second_person`, `second_person_count`) are consistently higher for toxic comments.
- Style/intensity indicators (`uppercase_ratio`, `exclamation_count`) are higher in toxic texts and support class separation.
- `profanity_count` is clearly higher in toxic comments and provides useful predictive information.
- Length-based features (`char_count`, `word_count`) are weaker and slightly lower for toxic comments on average.
- Correlation heatmap suggests redundancy among some engineered features (especially sentiment-related), so multicollinearity should be monitored.

**Short recommendations**
- Use class weighting and threshold tuning due to class imbalance.
- Start with a regularized baseline model and compare against a tree-based model.
- Evaluate with F1 and PR-AUC, not accuracy alone.

## EDA-5: Modeling Readiness Checklist

- Train/test split remains fixed and leakage-safe.
- Train set includes engineered features ready for model training.
- Test set remains raw for later pipeline-based `transform()`.
- Target imbalance is confirmed and should be handled in modeling (e.g., class weights/threshold tuning).
- Candidate feature set for first baseline can be taken from top-ranked features in EDA-4.
"""